"use client";

import { useState } from "react";
import { Controller, useForm, useWatch } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { CheckCircle, ChevronLeft, ChevronRight, Loader2, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import VehicleSelector from "./VehicleSelector";
import { bookingSchema, getBangkokDateString, type BookingSchemaInput, type BookingSchemaType } from "@/validations/booking";
import type { VehicleType } from "@/types";
import type { Locale } from "@/lib/locale";

const COUNTRIES = ["+66", "+44", "+1", "+61", "+49", "+33", "+81", "+86", "+65", "+60"];
const inputClass = "w-full rounded-xl border border-[#102326]/15 bg-[#f3eadb] px-3 py-3 text-sm text-[#102326] outline-none placeholder:text-[#102326]/35 focus:border-[#e46d52]";
const copy = {
  en: { steps: ["Journey", "Contact", "Review"], journey: "Tell us where you’re going.", contact: "How should we reach you?", review: "Check the details, then send.", date: "Pickup date", time: "Pickup time", adults: "Adults", children: "Children", vehicle: "Vehicle", pickup: "Pickup location", flight: "Flight number", hotel: "Hotel name", address: "Pickup address", dropoff: "Drop-off location", maps: "Google Maps link", fullName: "Full name", phone: "Phone", email: "Email (optional)", channel: "Contact channel", contactInfo: "Contact handle or number", notes: "Special requests", continue: "Continue", back: "Back", send: "Send booking request", noDeposit: "No deposit required. We’ll confirm your private ride before you travel.", success: "Your ride is on its way.", successText: "We’ll contact you within 1 minute. Keep this reference for your records.", reference: "Booking reference", whatsapp: "Confirm on WhatsApp" },
  th: { steps: ["การเดินทาง", "ข้อมูลติดต่อ", "ตรวจสอบ"], journey: "บอกเราเกี่ยวกับการเดินทางของคุณ", contact: "เราควรติดต่อคุณอย่างไร?", review: "ตรวจสอบข้อมูลก่อนส่ง", date: "วันที่รับ", time: "เวลารับ", adults: "ผู้ใหญ่", children: "เด็ก", vehicle: "ประเภทรถ", pickup: "จุดรับ", flight: "หมายเลขเที่ยวบิน", hotel: "ชื่อโรงแรม", address: "ที่อยู่จุดรับ", dropoff: "จุดส่ง", maps: "ลิงก์ Google Maps", fullName: "ชื่อ-นามสกุล", phone: "เบอร์โทรศัพท์", email: "อีเมล (ไม่บังคับ)", channel: "ช่องทางติดต่อ", contactInfo: "ไอดีหรือหมายเลขติดต่อ", notes: "คำขอพิเศษ", continue: "ถัดไป", back: "ย้อนกลับ", send: "ส่งคำขอจองรถ", noDeposit: "ไม่ต้องวางมัดจำ เราจะยืนยันรถส่วนตัวก่อนเดินทาง", success: "รถของคุณกำลังจะมาถึง", successText: "เราจะติดต่อคุณภายใน 1 นาที โปรดเก็บรหัสอ้างอิงนี้ไว้", reference: "รหัสการจอง", whatsapp: "ยืนยันผ่าน WhatsApp" },
} as const;

function ErrorText({ message }: { message?: string }) { return message ? <p role="alert" className="mt-1 text-xs text-red-600">{message}</p> : null; }

export default function BookingForm({ whatsapp, locale = "en" }: { whatsapp: string; locale?: Locale }) {
  const thai = locale === "th"; const t = thai ? copy.th : copy.en;
  const [step, setStep] = useState(0); const [status, setStatus] = useState<"idle" | "loading" | "success">("idle"); const [bookingRef, setBookingRef] = useState("");
  const { register, control, trigger, getValues, handleSubmit, formState: { errors } } = useForm<BookingSchemaInput, unknown, BookingSchemaType>({ resolver: zodResolver(bookingSchema), defaultValues: { phoneCountry: "+66", adultPassengers: 1, childPassengers: 0, vehicleType: "SUV", pickupType: "AIRPORT", contactChannel: "WHATSAPP", website: "" } });
  const pickupType = useWatch({ control, name: "pickupType" }); const contactChannel = useWatch({ control, name: "contactChannel" });
  const next = async (): Promise<void> => { const fields = step === 0 ? ["pickupDate", "pickupTime", "adultPassengers", "childPassengers", "vehicleType", "pickupDetail", "dropoffLocation", "mapsLink"] : ["fullName", "phoneCountry", "phone", "email", "contactChannel", "contactInfo"]; const valid = await trigger(fields as Array<keyof BookingSchemaInput>); if (valid) setStep((current) => Math.min(2, current + 1)); };
  const submit = async (data: BookingSchemaType) => { setStatus("loading"); try { const response = await fetch("/api/booking", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || "Unable to submit booking"); setBookingRef(result.bookingRef); setStatus("success"); toast.success(thai ? "ส่งคำขอจองรถแล้ว" : "Booking submitted successfully"); } catch (error) { setStatus("idle"); toast.error(error instanceof Error ? error.message : "Network error. Please try again."); } };
  if (status === "success") return <div className="rounded-[1.5rem] border border-[#102326]/15 bg-[#eadfce] p-8 text-center md:p-12"><CheckCircle className="mx-auto mb-5 text-[#79b8a7]" size={58} /><p className="mb-2 text-[11px] font-bold uppercase tracking-[0.2em] text-[#e46d52]">{thai ? "ยืนยันการเดินทางแล้ว" : "Journey confirmed"}</p><h2 className="text-4xl text-[#102326]">{t.success}</h2><p className="mx-auto mt-4 max-w-md text-sm leading-7 text-[#102326]/65">{t.successText}</p><div className="mx-auto my-7 max-w-xs rounded-xl border border-[#e46d52]/40 bg-[#f3eadb] px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#102326]/50">{t.reference}</p><p className="mt-1 font-mono text-xl font-bold tracking-wider text-[#e46d52]">{bookingRef}</p></div><a href={`https://wa.me/${whatsapp.replace(/[^0-9]/g, "")}?text=Hi%20my%20booking%20reference%20is%20${encodeURIComponent(bookingRef)}`} target="_blank" rel="noopener noreferrer" className="inline-flex rounded-full bg-[#e46d52] px-6 py-3 text-sm font-bold text-[#102326]">{t.whatsapp}</a></div>;
  const values = getValues();
  return <form onSubmit={handleSubmit(submit)} className="space-y-5"><div className="rounded-[1.5rem] border border-[#102326]/15 bg-[#eadfce] p-4 md:p-5"><div className="flex items-center justify-between gap-2">{t.steps.map((label, index) => <div key={label} className="flex flex-1 items-center gap-2"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-bold ${index <= step ? "bg-[#e46d52] text-[#102326]" : "bg-[#102326]/10 text-[#102326]/45"}`}>{index + 1}</div><span className={`hidden text-xs font-bold uppercase tracking-[0.1em] sm:block ${index === step ? "text-[#102326]" : "text-[#102326]/45"}`}>{label}</span>{index < 2 && <div className={`h-px flex-1 ${index < step ? "bg-[#e46d52]" : "bg-[#102326]/15"}`} />}</div>)}</div></div>
    {step === 0 && <section className="rounded-[1.5rem] border border-[#102326]/15 bg-[#eadfce] p-6"><p className="mb-2 text-[11px] font-bold uppercase tracking-[0.2em] text-[#e46d52]">{thai ? "ขั้นตอนที่ 1 / การเดินทาง" : "Step 1 / Journey"}</p><h2 className="mb-6 text-3xl text-[#102326]">{t.journey}</h2><div className="grid gap-4 sm:grid-cols-2"><label>{t.date}<input type="date" min={getBangkokDateString()} className={inputClass} {...register("pickupDate")} /><ErrorText message={errors.pickupDate?.message} /></label><label>{t.time}<input type="time" className={inputClass} {...register("pickupTime")} /><ErrorText message={errors.pickupTime?.message} /></label><label>{t.adults}<input type="number" min={1} max={9} className={inputClass} {...register("adultPassengers", { valueAsNumber: true })} /></label><label>{t.children}<input type="number" min={0} max={9} className={inputClass} {...register("childPassengers", { valueAsNumber: true })} /></label></div><div className="mt-6"><p className="mb-2 text-xs font-bold uppercase">{t.vehicle}</p><Controller name="vehicleType" control={control} render={({ field }) => <VehicleSelector value={field.value as VehicleType} onChange={field.onChange} error={errors.vehicleType?.message} locale={locale} />} /></div><div className="mt-6"><p className="mb-2 text-xs font-bold uppercase">{t.pickup}</p><div className="grid gap-2 sm:grid-cols-3">{(["AIRPORT", "HOTEL", "OTHER"] as const).map((type) => <label key={type} className="cursor-pointer rounded-xl border border-[#102326]/15 px-4 py-3 text-sm font-semibold"><input type="radio" value={type} className="mr-2" {...register("pickupType")} />{type === "AIRPORT" ? (thai ? "สนามบิน" : "Airport") : type === "HOTEL" ? (thai ? "โรงแรม" : "Hotel") : (thai ? "อื่นๆ" : "Other")}</label>)}</div></div><label className="mt-4 block">{pickupType === "AIRPORT" ? t.flight : pickupType === "HOTEL" ? t.hotel : t.address}<input className={inputClass} placeholder={pickupType === "AIRPORT" ? "e.g. TG208" : ""} {...register("pickupDetail")} /><ErrorText message={errors.pickupDetail?.message} /></label><label className="mt-4 block">{t.dropoff}<input className={inputClass} {...register("dropoffLocation")} /><ErrorText message={errors.dropoffLocation?.message} /></label><label className="mt-4 block">{t.maps}<input className={inputClass} {...register("mapsLink")} /></label></section>}
    {step === 1 && <section className="rounded-[1.5rem] border border-[#102326]/15 bg-[#eadfce] p-6"><p className="mb-2 text-[11px] font-bold uppercase tracking-[0.2em] text-[#e46d52]">{thai ? "ขั้นตอนที่ 2 / ข้อมูลติดต่อ" : "Step 2 / Contact"}</p><h2 className="mb-6 text-3xl text-[#102326]">{t.contact}</h2><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">{t.fullName}<input className={inputClass} {...register("fullName")} /><ErrorText message={errors.fullName?.message} /></label><label>{t.phone}<div className="flex gap-2"><select className={`${inputClass} w-28`} {...register("phoneCountry")}>{COUNTRIES.map((country) => <option key={country}>{country}</option>)}</select><input className={inputClass} {...register("phone")} /></div><ErrorText message={errors.phone?.message} /></label><label>{t.email}<input type="email" className={inputClass} {...register("email")} /></label><label>{t.channel}<select className={inputClass} {...register("contactChannel")}><option value="WHATSAPP">WhatsApp</option><option value="LINE">LINE</option><option value="WECHAT">WeChat</option><option value="EMAIL">Email</option></select></label><label>{contactChannel === "EMAIL" ? (thai ? "ที่อยู่อีเมล" : "Email address") : t.contactInfo}<input className={inputClass} {...register("contactInfo")} /><ErrorText message={errors.contactInfo?.message} /></label></div></section>}
    {step === 2 && <section className="rounded-[1.5rem] border border-[#102326]/15 bg-[#eadfce] p-6"><p className="mb-2 text-[11px] font-bold uppercase tracking-[0.2em] text-[#e46d52]">{thai ? "ขั้นตอนที่ 3 / ตรวจสอบ" : "Step 3 / Review"}</p><h2 className="mb-6 text-3xl text-[#102326]">{t.review}</h2><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[#f3eadb] p-4"><p className="text-xs">{thai ? "การเดินทาง" : "Journey"}</p><p>{values.pickupDate || "—"} {values.pickupTime || "—"}</p></div><div className="rounded-xl bg-[#f3eadb] p-4"><p className="text-xs">{thai ? "เส้นทาง" : "Route"}</p><p>{values.pickupDetail || values.pickupType || "—"} → {values.dropoffLocation || "—"}</p></div></div><label className="mt-5 block">{t.notes}<textarea rows={3} className={`${inputClass} resize-none`} {...register("notes")} /></label><div className="mt-5 flex items-start gap-3 rounded-xl bg-[#79b8a7]/15 p-4 text-sm"><ShieldCheck size={18} /> <span>{t.noDeposit}</span></div></section>}
    <div className="flex justify-between"><button type="button" onClick={() => setStep((current) => Math.max(0, current - 1))} disabled={step === 0 || status === "loading"} className="rounded-full border px-5 py-3 disabled:invisible"><ChevronLeft size={16} className="inline" /> {t.back}</button>{step < 2 ? <button type="button" onClick={next} className="rounded-full bg-[#e46d52] px-6 py-3 font-bold">{t.continue} <ChevronRight size={16} className="inline" /></button> : <button type="submit" disabled={status === "loading"} className="rounded-full bg-[#e46d52] px-6 py-3 font-bold">{status === "loading" ? <Loader2 size={16} className="inline animate-spin" /> : t.send}</button>}</div>
  </form>;
}
