import Link from "next/link";
import { ArrowUpRight, CarFront, Luggage, UsersRound } from "lucide-react";
import type { Locale } from "@/lib/locale";

const VEHICLES = [
  { type: "Sedan", passengers: "1–2", passengersTh: "1–2", luggage: "2 bags", luggageTh: "2 ใบ", price: "1,200", note: "A quiet, comfortable ride for couples and solo travellers.", noteTh: "รถเงียบและสะดวกสบาย เหมาะสำหรับคู่รักหรือเดินทางคนเดียว" },
  { type: "SUV", passengers: "1–4", passengersTh: "1–4", luggage: "4 bags", luggageTh: "4 ใบ", price: "1,300", note: "More room to stretch out after a long flight.", noteTh: "พื้นที่กว้างขึ้น ให้คุณพักผ่อนได้สบายหลังเที่ยวบินยาว", featured: true },
  { type: "Van", passengers: "1–9", passengersTh: "1–9", luggage: "8+ bags", luggageTh: "8+ ใบ", price: "1,400", note: "The easy choice for families, friends, and big luggage.", noteTh: "ตัวเลือกสบายสำหรับครอบครัว เพื่อน และสัมภาระจำนวนมาก" },
];

export default function VehicleCards({ locale = "en" }: { locale?: Locale }) {
  const thai = locale === "th";
  return <section className="bg-[#f3eadb] py-20 text-[#102326] md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="mb-11 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-[11px] font-bold uppercase tracking-[0.22em] text-[#e46d52]">{thai ? "เลือกรถที่เหมาะกับคุณ" : "Choose your space"}</p><h2 className="max-w-lg text-4xl leading-tight sm:text-5xl">{thai ? "รถดีๆ ทำให้การเดินทางดีขึ้น" : "A good ride sets the tone."}</h2></div><p className="max-w-sm text-sm leading-7 text-[#102326]/65">{thai ? "รถสะอาด ปลอดภัย พร้อมคนขับท้องถิ่นที่สื่อสารภาษาอังกฤษได้" : "Clean, insured vehicles and an English-speaking local driver for every private transfer."}</p></div><div className="grid gap-4 lg:grid-cols-3">{VEHICLES.map((vehicle) => <article key={vehicle.type} className={`group relative flex min-h-[340px] flex-col overflow-hidden rounded-[1.5rem] border p-6 transition-transform hover:-translate-y-1 ${vehicle.featured ? "border-[#e46d52] bg-[#0b2a2f] text-[#f3eadb]" : "border-[#102326]/15 bg-[#eadfce]"}`}>{vehicle.featured && <span className="absolute right-5 top-5 rounded-full bg-[#e46d52] px-3 py-1 text-[9px] font-bold uppercase tracking-[0.15em] text-[#102326]">{thai ? "ยอดนิยม" : "Most requested"}</span>}<div className={`mb-12 flex h-14 w-14 items-center justify-center rounded-full border ${vehicle.featured ? "border-[#e46d52] text-[#e46d52]" : "border-[#102326]/20 text-[#0b2a2f]"}`}><CarFront size={25} strokeWidth={1.5} /></div><h3 className="text-3xl">{vehicle.type}</h3><p className={`mt-2 max-w-xs text-sm leading-6 ${vehicle.featured ? "text-[#d9cbb8]" : "text-[#102326]/65"}`}>{thai ? vehicle.noteTh : vehicle.note}</p><div className={`mt-6 flex gap-4 border-t pt-4 text-xs ${vehicle.featured ? "border-[#f3eadb]/15 text-[#d9cbb8]" : "border-[#102326]/15 text-[#102326]/65"}`}><span className="inline-flex items-center gap-1.5"><UsersRound size={14} /> {thai ? vehicle.passengersTh : vehicle.passengers} {thai ? "คน" : "pax"}</span><span className="inline-flex items-center gap-1.5"><Luggage size={14} /> {thai ? vehicle.luggageTh : vehicle.luggage}</span></div><div className="mt-auto flex items-end justify-between pt-7"><div><p className={`text-[10px] uppercase tracking-[0.16em] ${vehicle.featured ? "text-[#d9cbb8]" : "text-[#102326]/55"}`}>{thai ? "เริ่มต้น" : "From"}</p><p className={`text-2xl ${vehicle.featured ? "text-[#f3eadb]" : "text-[#0b2a2f]"}`}>{vehicle.price} <span className="text-xs">THB</span></p></div><Link href="/booking" aria-label={`${thai ? "จองรถ" : "Book"} ${vehicle.type}`} className={`flex h-10 w-10 items-center justify-center rounded-full transition-colors ${vehicle.featured ? "bg-[#e46d52] text-[#102326] hover:bg-[#f28a70]" : "border border-[#102326]/20 text-[#0b2a2f] hover:border-[#e46d52] hover:text-[#e46d52]"}`}><ArrowUpRight size={17} /></Link></div></article>)}</div></div></section>;
}
